# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ChunkServer_pb2 as ChunkServer__pb2


class ChunkServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.heart = channel.unary_unary(
                '/ChunkServer.ChunkServer/heart',
                request_serializer=ChunkServer__pb2.Empty.SerializeToString,
                response_deserializer=ChunkServer__pb2.Reply.FromString,
                )
        self.get_key = channel.unary_unary(
                '/ChunkServer.ChunkServer/get_key',
                request_serializer=ChunkServer__pb2.Key.SerializeToString,
                response_deserializer=ChunkServer__pb2.Value.FromString,
                )
        self.insert_key = channel.unary_unary(
                '/ChunkServer.ChunkServer/insert_key',
                request_serializer=ChunkServer__pb2.Value.SerializeToString,
                response_deserializer=ChunkServer__pb2.Reply.FromString,
                )
        self.delete_key = channel.unary_unary(
                '/ChunkServer.ChunkServer/delete_key',
                request_serializer=ChunkServer__pb2.Key.SerializeToString,
                response_deserializer=ChunkServer__pb2.Reply.FromString,
                )
        self.update_key = channel.unary_unary(
                '/ChunkServer.ChunkServer/update_key',
                request_serializer=ChunkServer__pb2.Value.SerializeToString,
                response_deserializer=ChunkServer__pb2.Reply.FromString,
                )
        self.add_secondary = channel.unary_unary(
                '/ChunkServer.ChunkServer/add_secondary',
                request_serializer=ChunkServer__pb2.Secondary.SerializeToString,
                response_deserializer=ChunkServer__pb2.Reply.FromString,
                )
        self.add_mates = channel.unary_unary(
                '/ChunkServer.ChunkServer/add_mates',
                request_serializer=ChunkServer__pb2.Secondary.SerializeToString,
                response_deserializer=ChunkServer__pb2.Reply.FromString,
                )
        self.sync_mates = channel.unary_stream(
                '/ChunkServer.ChunkServer/sync_mates',
                request_serializer=ChunkServer__pb2.Empty.SerializeToString,
                response_deserializer=ChunkServer__pb2.Secondary.FromString,
                )
        self.sync_tables = channel.unary_stream(
                '/ChunkServer.ChunkServer/sync_tables',
                request_serializer=ChunkServer__pb2.Empty.SerializeToString,
                response_deserializer=ChunkServer__pb2.Value.FromString,
                )
        self.select_primary = channel.unary_unary(
                '/ChunkServer.ChunkServer/select_primary',
                request_serializer=ChunkServer__pb2.Secondary.SerializeToString,
                response_deserializer=ChunkServer__pb2.Secondary.FromString,
                )
        self.replace_primary = channel.unary_unary(
                '/ChunkServer.ChunkServer/replace_primary',
                request_serializer=ChunkServer__pb2.Primary.SerializeToString,
                response_deserializer=ChunkServer__pb2.Reply.FromString,
                )
        self.get_primary = channel.unary_unary(
                '/ChunkServer.ChunkServer/get_primary',
                request_serializer=ChunkServer__pb2.Empty.SerializeToString,
                response_deserializer=ChunkServer__pb2.Primary.FromString,
                )


class ChunkServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def heart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insert_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_secondary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_mates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sync_mates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sync_tables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def select_primary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def replace_primary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_primary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChunkServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'heart': grpc.unary_unary_rpc_method_handler(
                    servicer.heart,
                    request_deserializer=ChunkServer__pb2.Empty.FromString,
                    response_serializer=ChunkServer__pb2.Reply.SerializeToString,
            ),
            'get_key': grpc.unary_unary_rpc_method_handler(
                    servicer.get_key,
                    request_deserializer=ChunkServer__pb2.Key.FromString,
                    response_serializer=ChunkServer__pb2.Value.SerializeToString,
            ),
            'insert_key': grpc.unary_unary_rpc_method_handler(
                    servicer.insert_key,
                    request_deserializer=ChunkServer__pb2.Value.FromString,
                    response_serializer=ChunkServer__pb2.Reply.SerializeToString,
            ),
            'delete_key': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_key,
                    request_deserializer=ChunkServer__pb2.Key.FromString,
                    response_serializer=ChunkServer__pb2.Reply.SerializeToString,
            ),
            'update_key': grpc.unary_unary_rpc_method_handler(
                    servicer.update_key,
                    request_deserializer=ChunkServer__pb2.Value.FromString,
                    response_serializer=ChunkServer__pb2.Reply.SerializeToString,
            ),
            'add_secondary': grpc.unary_unary_rpc_method_handler(
                    servicer.add_secondary,
                    request_deserializer=ChunkServer__pb2.Secondary.FromString,
                    response_serializer=ChunkServer__pb2.Reply.SerializeToString,
            ),
            'add_mates': grpc.unary_unary_rpc_method_handler(
                    servicer.add_mates,
                    request_deserializer=ChunkServer__pb2.Secondary.FromString,
                    response_serializer=ChunkServer__pb2.Reply.SerializeToString,
            ),
            'sync_mates': grpc.unary_stream_rpc_method_handler(
                    servicer.sync_mates,
                    request_deserializer=ChunkServer__pb2.Empty.FromString,
                    response_serializer=ChunkServer__pb2.Secondary.SerializeToString,
            ),
            'sync_tables': grpc.unary_stream_rpc_method_handler(
                    servicer.sync_tables,
                    request_deserializer=ChunkServer__pb2.Empty.FromString,
                    response_serializer=ChunkServer__pb2.Value.SerializeToString,
            ),
            'select_primary': grpc.unary_unary_rpc_method_handler(
                    servicer.select_primary,
                    request_deserializer=ChunkServer__pb2.Secondary.FromString,
                    response_serializer=ChunkServer__pb2.Secondary.SerializeToString,
            ),
            'replace_primary': grpc.unary_unary_rpc_method_handler(
                    servicer.replace_primary,
                    request_deserializer=ChunkServer__pb2.Primary.FromString,
                    response_serializer=ChunkServer__pb2.Reply.SerializeToString,
            ),
            'get_primary': grpc.unary_unary_rpc_method_handler(
                    servicer.get_primary,
                    request_deserializer=ChunkServer__pb2.Empty.FromString,
                    response_serializer=ChunkServer__pb2.Primary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChunkServer.ChunkServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChunkServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def heart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/heart',
            ChunkServer__pb2.Empty.SerializeToString,
            ChunkServer__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/get_key',
            ChunkServer__pb2.Key.SerializeToString,
            ChunkServer__pb2.Value.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def insert_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/insert_key',
            ChunkServer__pb2.Value.SerializeToString,
            ChunkServer__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/delete_key',
            ChunkServer__pb2.Key.SerializeToString,
            ChunkServer__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/update_key',
            ChunkServer__pb2.Value.SerializeToString,
            ChunkServer__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_secondary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/add_secondary',
            ChunkServer__pb2.Secondary.SerializeToString,
            ChunkServer__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_mates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/add_mates',
            ChunkServer__pb2.Secondary.SerializeToString,
            ChunkServer__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sync_mates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChunkServer.ChunkServer/sync_mates',
            ChunkServer__pb2.Empty.SerializeToString,
            ChunkServer__pb2.Secondary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sync_tables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ChunkServer.ChunkServer/sync_tables',
            ChunkServer__pb2.Empty.SerializeToString,
            ChunkServer__pb2.Value.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def select_primary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/select_primary',
            ChunkServer__pb2.Secondary.SerializeToString,
            ChunkServer__pb2.Secondary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def replace_primary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/replace_primary',
            ChunkServer__pb2.Primary.SerializeToString,
            ChunkServer__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_primary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChunkServer.ChunkServer/get_primary',
            ChunkServer__pb2.Empty.SerializeToString,
            ChunkServer__pb2.Primary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
